# v${project.version}

# If enabled, more information will be printed
Debug: false

# Configure the corresponding language file, default to lang/default.yml
Language: default

# If enabled, the data will be saved in the database, and you will need to create your own database without creating tables
Sql: false
Url: 'jdbc:mysql://localhost:3306/mc_market?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'