package io.fireflyest.emberlib.config;

import java.io.IOException;
import java.io.Writer;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Messager;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import org.bukkit.configuration.file.YamlConfiguration;

import io.fireflyest.emberlib.config.annotation.Entry;
import io.fireflyest.emberlib.config.annotation.Yaml;
import io.fireflyest.emberlib.util.TextUtils;

/**
 * 配置文件生成注解处理
 * 
 * @author Fireflyest
 * @since 1.0
 */
@SupportedAnnotationTypes("io.fireflyest.emberlib.config.annotation.Yaml")
public class YamlProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // 当前处理器支持的所有注解种类
        for (TypeElement typeElement : annotations) {
            // 获得被该注解声明的元素
            for (Element element : roundEnv.getElementsAnnotatedWith(typeElement)) {
                this.processElement(element);
            }
        }
        return true;
    }

    /**
     * 处理被注解的类
     * 
     * @param element 元素
     */
    private void processElement(@Nonnull Element element) {
        final Messager messager = processingEnv.getMessager();
        messager.printMessage(Diagnostic.Kind.NOTE, "YamlProcessor.processElement(Element)");

        final Yaml yaml = element.getAnnotation(Yaml.class);
        final YamlGenerator generator = new YamlGenerator(element, yaml.value());

        // 遍历所有变量
        final TypeElement classElement = ((TypeElement) element);
        for (Element enclosedElement : classElement.getEnclosedElements()) {
            if (enclosedElement.getKind() == ElementKind.FIELD) {
                final VariableElement variableElement = ((VariableElement) enclosedElement);
                final Entry entry = variableElement.getAnnotation(Entry.class);
                if (entry == null) {
                    continue;
                }
                final String key = "".equals(entry.value()) 
                    ? variableElement.getSimpleName().toString() : entry.value();
                generator.set(key, variableElement.getConstantValue());
            }
        }

        try {
            generator.write();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    /**
     * 配置文件生成器
     * 
     * @since 1.0
     */
    private class YamlGenerator {
        
        /**
         * 配置文件
         */
        private final YamlConfiguration yaml = new YamlConfiguration();

        /**
         * 被注释的类元素
         */
        private final Element element;

        /**
         * 保存文件路径
         */
        private final String targetFile;

        /**
         * 生成器构造
         * 
         * @param element 被注释的类元素
         * @param targetFile 保存文件路径
         */
        public YamlGenerator(@Nonnull Element element, @Nonnull String targetFile) {
            this.element = element;
            this.targetFile = targetFile;
        }

        /**
         * 设置键值
         * 
         * @param key 键
         * @param value 值
         */
        public void set(@Nonnull String key, Object value) {
            yaml.set(TextUtils.upperFirst(TextUtils.toCamel(key)), value);
        }

        /**
         * 写入文件
         * 
         * @throws IOException 文件传输错误
         */
        public void write() throws IOException {
            final FileObject fileObject = processingEnv.getFiler().createResource(
                StandardLocation.CLASS_OUTPUT, 
                "", 
                targetFile, 
                element
            );
            final Writer writer = fileObject.openWriter();
            writer.write("# generated by EmberLib\n");
            writer.write(yaml.saveToString());
            writer.flush();
            writer.close();
        }
        
    }
    
}
